### ISSUE TITLE
Error _faction undefined variable

### ISSUE THREAD

**Issue by Churrofighter** [1ncontinentia/INC_Scripts_A3#23]
Hi, no matter what I do, I keep getting and getting these errors:

![error](https://user-images.githubusercontent.com/9594604/32273890-9bec9846-bf04-11e7-9b19-b5aa7c45e340.png)

I have correctly set up the _asymSide and the _asymFaction in INT_setup.sqf. Using CUP Units by the way.

**Comment by 1ncontinentia** [comment]
So, even with the most basic setup using the script vanilla you get this?

**Comment by Churrofighter** [comment]
> So, even with the most basic setup using the script vanilla you get this?

Yes, just using CBA+ALIVE: https://drive.google.com/open?id=1y9JBCE0aNkQM5QthndzwQjDx6LiqDqLq

**Comment by 1ncontinentia** [comment]
Did you read the readme out of interest? Not to be patronising or anything but it's worth checking...

**Comment by Churrofighter** [comment]
Yes, of course; I've set the variables in the INT_Setup.sqf: 

_asymSide = east; //Which side is asymmetric (1 side only, can be east, west, independent or sideEmpty)
_asymFaction = OPF_F;  //Which factions is asymmetric (1 faction only for now)

**Comment by 1ncontinentia** [comment]
This [readme](https://github.com/1ncontinentia/INC_Scripts_A3/blob/master/README.md)? Or are you using the standalone version? If you are using this version, be aware that it isn't supported anymore. [This is the version you'll want to use](https://github.com/1ncontinentia/Incon-Undercover). Let me know on that repo if you're still having issues. Apologies for not noticing this sooner if that is the issue; I don't have a PC anymore so honestly didn't think to check which version you were using.

**Comment by 1ncontinentia** [comment]
I'll close this issue as it's either unsupported or in the wrong place. Feel free to open one on the other repo if you're having issues still using that version.
